---

- name: Manage OPNsense firewall
  hosts: [ 'platform_opnsense' ]
  gather_facts: True
  strategy: 'linear'
  become: False

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Update Ansible facts
      setup:
      tags: ['facts']

  roles:

    - role: opnsense
      tags: ['role::opnsense']

    - role: opnsense_plugpack
      tags: ['role::opnsense_plugpack']
