---

- name: Configure RustDesk client
  hosts: [ 'ypid_service_rustdesk' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ypid.rustdesk
