---

- name: Install Wordpress
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]
  hosts: [ 'ypid_service_wordpress' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Apply keyring configuration for php environment
      import_role:
        name: 'keyring'
      vars:
        keyring__dependent_apt_keys:
          - '{{ php__keyring__dependent_apt_keys }}'
      tags: [ 'role::keyring', 'skip::keyring', 'role::php' ]

    - name: Prepare php environment
      import_role:
        name: 'php'
        tasks_from: 'main_env'
      tags: [ 'role::php', 'role::php:env', 'role::logrotate' ]

  roles:

    - role: mariadb
      tags: [ 'role::mariadb', 'skip::mariadb' ]
      mariadb__dependent_databases:
        - '{{ wordpress__mariadb__dependent_databases }}'
      mariadb__dependent_users:
        - '{{ wordpress__mariadb__dependent_users }}'

    - role: php
      tags: [ 'role::php', 'skip::php' ]
      php__dependent_packages:
        - '{{ wordpress__php__dependent_packages }}'
      php__dependent_pools:
        - '{{ wordpress__php__dependent_pools }}'
      php__ini_memory_limit: '{{ wordpress__php__memory_limit }}'
      php__ini_post_max_size: '{{ wordpress__php__post_max_size }}'

    - role: nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx_acme: False
      nginx_acme_root: '{{ wordpress__nginx__acme_root }}'
      nginx__default_servers: []
      nginx__default_upstreams: []
      nginx__dependent_servers:
        - '{{ wordpress__nginx__dependent_servers }}'
      nginx__dependent_upstreams:
        - '{{ wordpress__nginx__dependent_upstreams }}'
      nginx__internal_servers: []
      nginx_pki_realm: '{{ wordpress__nginx__pki_realm }}'
      nginx_user: '{{ wordpress__nginx__user }}'
      nginx_webroot_create: False
      nginx_www: '{{ wordpress__nginx__www }}'

    - role: wpcli
      tags: [ 'role::wpcli', 'skip::wpcli' ]

    - role: wordpress
      tags: [ 'role::wordpress', 'skip::wordpress' ]
